# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Santoso's Pensieve
subtitle: "v0.1.0"
email: code@swijaya.me
description: >- # this means to ignore newlines until "baseurl:"
  A [pensieve](https://www.wizardingworld.com/fact-file/objects/pensieve#) for
  my thoughts and ramblings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pensieve.swijaya.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  santoso-wijaya
repository: "santoso-wijaya/pensieve"
#logo: "/assets/logo/pensieve-88x88.png" # Site masthead logo

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-badges
  - jekyll-feed
  - jekyll-include-cache # required for minimal-mistakes-jekyll!
  - jekyll-responsive-image

minimal_mistakes_skin: "air"

# For customizing minimal-mistakes theme features in this file, see:
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

timezone: America/Los_Angeles

author: Santoso Wijaya

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/santoso-wijaya"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/cygnoid9"

# Archive Settings
# See: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy  # provided by Minimal Mistakes
    tag: archive-taxonomy # see: _layouts folder in minimal-mistakes-jekyll gem
  permalinks:
    category: /categories/:name/ # e.g. pensieve.swijaya.me/categories/keebs/
    tag: /tags/:name/

# Configure our Jekyll Collections structure.
collections_dir: collections
collections:
  # for /collections/<category>/<sub_category>/_posts/yyyy-mm-dd-title.md
  posts:
    output: true
    permalink: /:categories/:title
  # for /collections/nihongo/... collection of pages
  nihongo:
    # these say: output `index.html` files for each document in
    # /collections/_nihongo/<document_filename>/
    output: true
    permalink: /:collection/:path

# Front Matter Defaults.
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values: # by default, set the following options in Front Matter of all posts
      layout: single
      author_profile: true
      show_date: true
      read_time: true # the default word/minute value is 200
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # The following two "empty path" scopes apply FM defaults to jekyll-archives
  # generated pages.
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: false
  # Collection defaults for _nihongo
  - scope:
      path: ""
      type: nihongo
    values:
      layout: single
      author_profile: false
      share: true

# Reading files
include:
  - _pages
exclude:
  # Note: dotfiles are already excluded by default.
  - README.md


# jekyll-responsive-image configs
responsive_image:
  template: _includes/responsive-image.html
  # Quality to use when resizing images.
  default_quality: 80
  sizes:
    - width: 480
    - width: 800
      quality: 90
    - width: 1400
      quality: 90
  # Don't save resized images to source.
  save_to_source: false
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/avatars/*.{jpeg,jpg}
